seed: 18591845184
#seed: 97763026622289

run_name: crosslink_test
n_dim: 2
n_periodic: 2
delta: 0.0001
n_steps: 50000
n_steps_target: 100000
boundary: 0
n_update_cells: -1
cell_length: 4
movie_flag: 0

graph_flag: 1
n_graph: 100
graph_background: 0
print_complete: 1

system_radius: 100
potential: soft
soft_potential_mag: 15
soft_potential_mag_target: -1
like_like_interactions: 1
stoch_flag: 1
f_cutoff: 10000
n_thermo: 100
thermo_flag: 1
local_order_analysis: 0
local_order_bin_width: 0.5
local_order_width: 40
local_order_average: 1
interaction_flag: 1
overlap_analysis: 0
density_analysis: 0
density_com_only: 0
density_bin_width: 0.1
in_out_flag: 1

crosslink:
  concentration: 0.01
  diameter: 1.5
  draw_type: fixed
  color: 3.14
  walker: 1
  step_direction: 1
  diffusion_flag: 1
  velocity: 10

filament:
  num: 2
  packing_fraction: -1
  overlap: 0
  insertion_type: custom
  insert_file: crosslink_filament.yaml
  diameter: 1
  length: 50
  perlen_ratio: 100
  perlen_ratio_target: -1
  #intrinsic_curvature: .0628
  n_bonds: 17
  driving_factor: 0
  n_spec: 100
  n_checkpoint: 100
  spec_flag: 1
  checkpoint_flag: 1
  flagella_flag: 0
  flagella_freq: 0.1
  flagella_period: 2
  flagella_amplitude: 3

motor:
  draw_type: bw
  diameter: 2
  walker: 1
  step_direction: 1
  k_off: 0.1
  k_on: 10
  concentration: 0
  velocity: 10
  diffusion_flag: 1
  k_spring: 1000
  f_spring_max: 500
# Outputs
  posit_flag: 1
  spec_flag: 1
  checkpoint_flag: 1
  n_posit: 1000
  n_spec: 1000
  n_checkpoint: 1000

